source "https://rubygems.org"

gem "sinatra"
gem "sinatra-twitter-bootstrap", :require => "sinatra/twitter-bootstrap"

gem "haml"

group :test, :development do
  gem "zip-zip"
  gem "warbler"

  gem "rack-test"
  gem "rspec"
end
